### ISSUE TITLE
Django 1.10 Support 

### ISSUE THREAD

**Issue by scherrey** [bernardopires/django-tenant-schemas#368]
First cursory check in trying to get working with Django 1.10 (which just went into production) doesn't seem to get along. Anyone else have the same problem? Tried with tenant 1.6.2.

This is error
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sakgunner/.virtualenvs/spike-1170/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/sakgunner/.virtualenvs/spike-1170/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sakgunner/.virtualenvs/spike-1170/lib/python3.4/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/sakgunner/.virtualenvs/spike-1170/lib/python3.4/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    return module.Command()
  File "/home/sakgunner/.virtualenvs/spike-1170/lib/python3.4/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 16, in init
    self.option_list += MigrateCommand.option_list
AttributeError: 'Command' object has no attribute 'option_list'

**Comment by aman0511** [comment]
Is any body got the solution for this?

**Comment by yushkovskiy** [comment]
As I understood you just need to remove this line:
/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 16
```
        #self.option_list += MigrateCommand.option_list 
```
because management command doesn't need to update this explicitly any more. It works for me, but it would be greate if someone would add version check to support for older version of django, run tests and make a PR

**Comment by demiurg** [comment]
Two pull requests now :)

**Comment by bernardopires** [comment]
Should be working now!
