### ISSUE TITLE
Django 1.8

### ISSUE THREAD

**Issue by tomturner** [bernardopires/django-tenant-schemas#252]
As Django 1.8 is out. I have just tried django-tenant-schemas example and it doesn't work.

When running python manage.py migrate_schemas I get the following error

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/tenant_schemas/management/commands/migrate_schemas.py", line 24, in run_from_argv
    super(MigrateSchemasCommand, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/tenant_schemas/management/commands/migrate_schemas.py", line 34, in handle
    self.run_migrations(self.schema_name, settings.SHARED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/tenant_schemas/management/commands/migrate_schemas.py", line 61, in run_migrations
    command.execute(*self.args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 70, in handle
    connection = connections[db]
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 234, in __getitem__
    if hasattr(self._connections, alias):
TypeError: hasattr(): attribute name must be string
```
And if I take an existing project from 1.7 and do run sever I get
```
System check identified no issues (0 silenced).
Unhandled exception in thread started by <function wrapper at 0xb617ca04>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 223, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 164, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 180, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/introspection.py", line 58, in table_names
    return get_names(cursor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/introspection.py", line 53, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/introspection.py", line 54, in <genexpr>
    if include_views or ti.type == 't')
AttributeError: 'unicode' object has no attribute 'type' 
```

**Comment by flxfxp** [comment]
I run into the same problem, does anyone know how to fix the migrate command under 1.8? Thanks!

**Comment by tomturner** [comment]
I have got it to work see https://github.com/tomturner/django-tenant-schemas/commit/fe437f7c81af8484614b3dcdaeb7ad5c43249f54

**Comment by flxfxp** [comment]
Sweet! Care to create a pull request @tomturner ?

**Comment by tomturner** [comment]
The problem with my fix is that it wont work with Django 1.7

**Comment by mickeyckm** [comment]
Any chance this will be fix soon?

**Comment by tomturner** [comment]
I have now created a pull request for Django 1.8 as I just made it work for Django 1.7 etc

**Comment by brechmos** [comment]
@tomturner thank you for fixing this.  Very helpful as I am just trying out python3.4 and django1.8 with tenant schemas (which is awesome).

**Comment by tomturner** [comment]
As this project isn't being work on I have created a new one for Django 1.8 or above is at https://github.com/tomturner/django-tenants and you can pip install django-tenants

**Comment by ablochs** [comment]
hey @tomturner, the link seems to be broken https://github.com/tomturner/django-tenant-schemas/commit/fe437f7c81af8484614b3dcdaeb7ad5c43249f54

im trying to make it work with django 1.8...

**Comment by ablochs** [comment]
ok found it... https://github.com/bernardopires/django-tenant-schemas/commit/c80f5a2608bf75af0cabfd2a3d9704ef0ea22d0b

**Comment by bernardopires** [comment]
Support for django 1.8 has been added.
