### ISSUE TITLE
Support for Django 2.0

### ISSUE THREAD

**Issue by jaimesanz** [bernardopires/django-tenant-schemas#544]
Are there any plans to support django 2.0 in the near future?

**Comment by dmwyatt** [comment]
I'd consider working on it if there was a list of blocking issues (if any).

**Comment by pvandegeer** [comment]
I've been using it in a dev environment for a couple of weeks now and its working fine on Django 2.0 with this patch applied:
https://github.com/bernardopires/django-tenant-schemas/pull/519

Might be al that's needed.

**Comment by imatsu** [comment]
Support for PostgreSQL 10?

**Comment by User3759685** [comment]
Works fine for me with Django 2.0.7 and PostgreSQL 10.4 and django-tenant-schemas 1.9.0.

**Comment by riparian-imakedonsky** [comment]
I'm also having no issues on Django 2.0.4, postgrsql 10.3 and package 1.9.0

**Comment by LorisLunedei** [comment]
Hi, I'm using Django 2.1.2 and I have problems with the 'Specializing templates based on tenants' feature.
When I add the `tenant_schemas.template_loaders.FilesystemLoader`  loader I receive this error:
`'FilesystemLoader' object has no attribute 'get_contents'`

It seems that in the newest django versions loader mechanism is changed a little (or I'm doing something wrong?).

That's my template configuration:
```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'OPTIONS': {
            'loaders': [
                'tenant_schemas.template_loaders.FilesystemLoader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader'
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

**Comment by kabaltech** [comment]
Any plans to support django >= 2.0?

**Comment by ibrobabs** [comment]
Any plans to support Django >= 2.0??

**Comment by Jaroslav84** [comment]
works
